/*
 * generated by Xtext 2.21.0
 */
package com.example.specs.ui;

import com.example.specs.ui.internal.SpecsActivator;
import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SpecsDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(SpecsActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		SpecsActivator activator = SpecsActivator.getInstance();
		return activator != null ? activator.getInjector(SpecsActivator.COM_EXAMPLE_SPECS_SPECSDSL) : null;
	}

}
