/*
 * generated by Xtext 2.21.0
 */
package com.example.specs;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SpecsDslStandaloneSetup extends SpecsDslStandaloneSetupGenerated {

	public static void doSetup() {
		new SpecsDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
