/*
 * generated by Xtext 2.21.0
 */
package com.example.specs.ide;


/**
 * Use this class to register ide components.
 */
public class SpecsDslIdeModule extends AbstractSpecsDslIdeModule {
	
	
}
