/*
 * generated by Xtext 2.21.0
 */
package com.example.specs.ide;

import com.example.specs.SpecsDslRuntimeModule;
import com.example.specs.SpecsDslStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SpecsDslIdeSetup extends SpecsDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SpecsDslRuntimeModule(), new SpecsDslIdeModule()));
	}
	
}
