/*
 * generated by Xtext 2.21.0
 */
package com.example.specs.parser.antlr;

import com.example.specs.parser.antlr.internal.InternalSpecsDslParser;
import com.example.specs.services.SpecsDslGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SpecsDslParser extends AbstractAntlrParser {

	@Inject
	private SpecsDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSpecsDslParser createParser(XtextTokenStream stream) {
		return new InternalSpecsDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public SpecsDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SpecsDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
