/**
 * generated by Xtext 2.21.0
 */
package com.example.specs.specsDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Clock Speed</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.example.specs.specsDsl.ClockSpeed#getClockSpeed <em>Clock Speed</em>}</li>
 * </ul>
 *
 * @see com.example.specs.specsDsl.SpecsDslPackage#getClockSpeed()
 * @model
 * @generated
 */
public interface ClockSpeed extends EObject
{
  /**
   * Returns the value of the '<em><b>Clock Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Clock Speed</em>' attribute.
   * @see #setClockSpeed(float)
   * @see com.example.specs.specsDsl.SpecsDslPackage#getClockSpeed_ClockSpeed()
   * @model
   * @generated
   */
  float getClockSpeed();

  /**
   * Sets the value of the '{@link com.example.specs.specsDsl.ClockSpeed#getClockSpeed <em>Clock Speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Clock Speed</em>' attribute.
   * @see #getClockSpeed()
   * @generated
   */
  void setClockSpeed(float value);

} // ClockSpeed
