/**
 * generated by Xtext 2.21.0
 */
package com.example.specs.specsDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cores</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.example.specs.specsDsl.Cores#getCores <em>Cores</em>}</li>
 * </ul>
 *
 * @see com.example.specs.specsDsl.SpecsDslPackage#getCores()
 * @model
 * @generated
 */
public interface Cores extends EObject
{
  /**
   * Returns the value of the '<em><b>Cores</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cores</em>' attribute.
   * @see #setCores(int)
   * @see com.example.specs.specsDsl.SpecsDslPackage#getCores_Cores()
   * @model
   * @generated
   */
  int getCores();

  /**
   * Sets the value of the '{@link com.example.specs.specsDsl.Cores#getCores <em>Cores</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cores</em>' attribute.
   * @see #getCores()
   * @generated
   */
  void setCores(int value);

} // Cores
