/**
 * generated by Xtext 2.21.0
 */
package com.example.specs.specsDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Memory</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.example.specs.specsDsl.Memory#getName <em>Name</em>}</li>
 *   <li>{@link com.example.specs.specsDsl.Memory#getCapacity <em>Capacity</em>}</li>
 * </ul>
 *
 * @see com.example.specs.specsDsl.SpecsDslPackage#getMemory()
 * @model
 * @generated
 */
public interface Memory extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' reference.
   * @see #setName(com.example.library.Memory)
   * @see com.example.specs.specsDsl.SpecsDslPackage#getMemory_Name()
   * @model
   * @generated
   */
  com.example.library.Memory getName();

  /**
   * Sets the value of the '{@link com.example.specs.specsDsl.Memory#getName <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' reference.
   * @see #getName()
   * @generated
   */
  void setName(com.example.library.Memory value);

  /**
   * Returns the value of the '<em><b>Capacity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Capacity</em>' containment reference.
   * @see #setCapacity(Capacity)
   * @see com.example.specs.specsDsl.SpecsDslPackage#getMemory_Capacity()
   * @model containment="true"
   * @generated
   */
  Capacity getCapacity();

  /**
   * Sets the value of the '{@link com.example.specs.specsDsl.Memory#getCapacity <em>Capacity</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Capacity</em>' containment reference.
   * @see #getCapacity()
   * @generated
   */
  void setCapacity(Capacity value);

} // Memory
