/**
 * generated by Xtext 2.21.0
 */
package com.example.specs.specsDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Motherboard</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.example.specs.specsDsl.Motherboard#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see com.example.specs.specsDsl.SpecsDslPackage#getMotherboard()
 * @model
 * @generated
 */
public interface Motherboard extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' reference.
   * @see #setName(com.example.library.Motherboard)
   * @see com.example.specs.specsDsl.SpecsDslPackage#getMotherboard_Name()
   * @model
   * @generated
   */
  com.example.library.Motherboard getName();

  /**
   * Sets the value of the '{@link com.example.specs.specsDsl.Motherboard#getName <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' reference.
   * @see #getName()
   * @generated
   */
  void setName(com.example.library.Motherboard value);

} // Motherboard
