/**
 * generated by Xtext 2.21.0
 */
package com.example.specs.specsDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Processor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.example.specs.specsDsl.Processor#getName <em>Name</em>}</li>
 *   <li>{@link com.example.specs.specsDsl.Processor#getClockSpeed <em>Clock Speed</em>}</li>
 *   <li>{@link com.example.specs.specsDsl.Processor#getCores <em>Cores</em>}</li>
 * </ul>
 *
 * @see com.example.specs.specsDsl.SpecsDslPackage#getProcessor()
 * @model
 * @generated
 */
public interface Processor extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' reference.
   * @see #setName(com.example.library.Processor)
   * @see com.example.specs.specsDsl.SpecsDslPackage#getProcessor_Name()
   * @model
   * @generated
   */
  com.example.library.Processor getName();

  /**
   * Sets the value of the '{@link com.example.specs.specsDsl.Processor#getName <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' reference.
   * @see #getName()
   * @generated
   */
  void setName(com.example.library.Processor value);

  /**
   * Returns the value of the '<em><b>Clock Speed</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Clock Speed</em>' containment reference.
   * @see #setClockSpeed(ClockSpeed)
   * @see com.example.specs.specsDsl.SpecsDslPackage#getProcessor_ClockSpeed()
   * @model containment="true"
   * @generated
   */
  ClockSpeed getClockSpeed();

  /**
   * Sets the value of the '{@link com.example.specs.specsDsl.Processor#getClockSpeed <em>Clock Speed</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Clock Speed</em>' containment reference.
   * @see #getClockSpeed()
   * @generated
   */
  void setClockSpeed(ClockSpeed value);

  /**
   * Returns the value of the '<em><b>Cores</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cores</em>' containment reference.
   * @see #setCores(Cores)
   * @see com.example.specs.specsDsl.SpecsDslPackage#getProcessor_Cores()
   * @model containment="true"
   * @generated
   */
  Cores getCores();

  /**
   * Sets the value of the '{@link com.example.specs.specsDsl.Processor#getCores <em>Cores</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cores</em>' containment reference.
   * @see #getCores()
   * @generated
   */
  void setCores(Cores value);

} // Processor
