/*
 * generated by Xtext 2.21.0
 */
package com.example.specs.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SpecsDslUiModule extends AbstractSpecsDslUiModule {

	public SpecsDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
