/*
 * generated by Xtext 2.21.0
 */
package com.example.specs.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSpecsDslScopeProvider extends DelegatingScopeProvider {
}
